stages:
  raw_dataset_creation:
    cmd: python src/data/load.py --config=params.yaml
    deps:
    - src/data/load.py
    - data/external/train.csv
    outs:
    - data/raw/train.csv
  
  split_data:
    cmd: python src/data/split.py --config=params.yaml
    deps:
    - src/data/split.py
    - data/raw/train.csv
    outs:
    - data/processed/exited_train.csv
    - data/processed/exited_test.csv

  model_train:
    cmd: python src/models/train_model.py --config=params.yaml
    deps:
    - data/processed/exited_train.csv
    - data/processed/exited_test.csv
    - src/models/train_model.py
    params:
    - random_forest.max_depth
    - random_forest.n_estimators

  # log_production_model:
  #   cmd: python src/models/production_model_selection.py --config=params.yaml
  #   deps:
  #   - src/models/production_model_selection.py
  #   params:
  #   - random_forest.max_depth
  #   - random_forest.n_estimators
  #   outs:
  #   - models/model.joblib